/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcingRouteImport } from './routes/sourcing'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MlmRouteImport } from './routes/mlm'
import { Route as GroupageRouteImport } from './routes/groupage'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as PaymentCallbackRouteImport } from './routes/payment.callback'
import { Route as CheckoutOrderIdRouteImport } from './routes/checkout.$orderId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSourcingRouteImport } from './routes/admin.sourcing'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminProofsRouteImport } from './routes/admin.proofs'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPaymentMethodsRouteImport } from './routes/admin.payment-methods'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminCommissionsRouteImport } from './routes/admin.commissions'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminCampaignProductsRouteImport } from './routes/admin.campaign-products'
import { Route as ApiPublicWebhooksGeniuspayRouteImport } from './routes/api/public/webhooks/geniuspay'

const SourcingRoute = SourcingRouteImport.update({
  id: '/sourcing',
  path: '/sourcing',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MlmRoute = MlmRouteImport.update({
  id: '/mlm',
  path: '/mlm',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupageRoute = GroupageRouteImport.update({
  id: '/groupage',
  path: '/groupage',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment/callback',
  path: '/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutOrderIdRoute = CheckoutOrderIdRouteImport.update({
  id: '/checkout/$orderId',
  path: '/checkout/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSourcingRoute = AdminSourcingRouteImport.update({
  id: '/sourcing',
  path: '/sourcing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProofsRoute = AdminProofsRouteImport.update({
  id: '/proofs',
  path: '/proofs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentMethodsRoute = AdminPaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignProductsRoute = AdminCampaignProductsRouteImport.update({
  id: '/campaign-products',
  path: '/campaign-products',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicWebhooksGeniuspayRoute =
  ApiPublicWebhooksGeniuspayRouteImport.update({
    id: '/api/public/webhooks/geniuspay',
    path: '/api/public/webhooks/geniuspay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/groupage': typeof GroupageRoute
  '/mlm': typeof MlmRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sourcing': typeof SourcingRoute
  '/admin/campaign-products': typeof AdminCampaignProductsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/proofs': typeof AdminProofsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/sourcing': typeof AdminSourcingRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/webhooks/geniuspay': typeof ApiPublicWebhooksGeniuspayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/groupage': typeof GroupageRoute
  '/mlm': typeof MlmRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sourcing': typeof SourcingRoute
  '/admin/campaign-products': typeof AdminCampaignProductsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/proofs': typeof AdminProofsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/sourcing': typeof AdminSourcingRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/product/$id': typeof ProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/webhooks/geniuspay': typeof ApiPublicWebhooksGeniuspayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/groupage': typeof GroupageRoute
  '/mlm': typeof MlmRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sourcing': typeof SourcingRoute
  '/admin/campaign-products': typeof AdminCampaignProductsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/proofs': typeof AdminProofsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/sourcing': typeof AdminSourcingRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/webhooks/geniuspay': typeof ApiPublicWebhooksGeniuspayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/groupage'
    | '/mlm'
    | '/orders'
    | '/profile'
    | '/sitemap.xml'
    | '/sourcing'
    | '/admin/campaign-products'
    | '/admin/campaigns'
    | '/admin/commissions'
    | '/admin/orders'
    | '/admin/payment-methods'
    | '/admin/products'
    | '/admin/proofs'
    | '/admin/roles'
    | '/admin/sourcing'
    | '/admin/users'
    | '/checkout/$orderId'
    | '/payment/callback'
    | '/product/$id'
    | '/admin/'
    | '/api/public/webhooks/geniuspay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/groupage'
    | '/mlm'
    | '/orders'
    | '/profile'
    | '/sitemap.xml'
    | '/sourcing'
    | '/admin/campaign-products'
    | '/admin/campaigns'
    | '/admin/commissions'
    | '/admin/orders'
    | '/admin/payment-methods'
    | '/admin/products'
    | '/admin/proofs'
    | '/admin/roles'
    | '/admin/sourcing'
    | '/admin/users'
    | '/checkout/$orderId'
    | '/payment/callback'
    | '/product/$id'
    | '/admin'
    | '/api/public/webhooks/geniuspay'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/groupage'
    | '/mlm'
    | '/orders'
    | '/profile'
    | '/sitemap.xml'
    | '/sourcing'
    | '/admin/campaign-products'
    | '/admin/campaigns'
    | '/admin/commissions'
    | '/admin/orders'
    | '/admin/payment-methods'
    | '/admin/products'
    | '/admin/proofs'
    | '/admin/roles'
    | '/admin/sourcing'
    | '/admin/users'
    | '/checkout/$orderId'
    | '/payment/callback'
    | '/product/$id'
    | '/admin/'
    | '/api/public/webhooks/geniuspay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  GroupageRoute: typeof GroupageRoute
  MlmRoute: typeof MlmRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SourcingRoute: typeof SourcingRoute
  CheckoutOrderIdRoute: typeof CheckoutOrderIdRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiPublicWebhooksGeniuspayRoute: typeof ApiPublicWebhooksGeniuspayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sourcing': {
      id: '/sourcing'
      path: '/sourcing'
      fullPath: '/sourcing'
      preLoaderRoute: typeof SourcingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mlm': {
      id: '/mlm'
      path: '/mlm'
      fullPath: '/mlm'
      preLoaderRoute: typeof MlmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groupage': {
      id: '/groupage'
      path: '/groupage'
      fullPath: '/groupage'
      preLoaderRoute: typeof GroupageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/callback': {
      id: '/payment/callback'
      path: '/payment/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$orderId': {
      id: '/checkout/$orderId'
      path: '/checkout/$orderId'
      fullPath: '/checkout/$orderId'
      preLoaderRoute: typeof CheckoutOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sourcing': {
      id: '/admin/sourcing'
      path: '/sourcing'
      fullPath: '/admin/sourcing'
      preLoaderRoute: typeof AdminSourcingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/proofs': {
      id: '/admin/proofs'
      path: '/proofs'
      fullPath: '/admin/proofs'
      preLoaderRoute: typeof AdminProofsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payment-methods': {
      id: '/admin/payment-methods'
      path: '/payment-methods'
      fullPath: '/admin/payment-methods'
      preLoaderRoute: typeof AdminPaymentMethodsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaign-products': {
      id: '/admin/campaign-products'
      path: '/campaign-products'
      fullPath: '/admin/campaign-products'
      preLoaderRoute: typeof AdminCampaignProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/webhooks/geniuspay': {
      id: '/api/public/webhooks/geniuspay'
      path: '/api/public/webhooks/geniuspay'
      fullPath: '/api/public/webhooks/geniuspay'
      preLoaderRoute: typeof ApiPublicWebhooksGeniuspayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCampaignProductsRoute: typeof AdminCampaignProductsRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentMethodsRoute: typeof AdminPaymentMethodsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminProofsRoute: typeof AdminProofsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSourcingRoute: typeof AdminSourcingRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCampaignProductsRoute: AdminCampaignProductsRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentMethodsRoute: AdminPaymentMethodsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminProofsRoute: AdminProofsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSourcingRoute: AdminSourcingRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  GroupageRoute: GroupageRoute,
  MlmRoute: MlmRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SourcingRoute: SourcingRoute,
  CheckoutOrderIdRoute: CheckoutOrderIdRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  ProductIdRoute: ProductIdRoute,
  ApiPublicWebhooksGeniuspayRoute: ApiPublicWebhooksGeniuspayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
