/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcingRouteImport } from './routes/sourcing'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MlmRouteImport } from './routes/mlm'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as GroupageRouteImport } from './routes/groupage'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CargoRouteImport } from './routes/Cargo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HotelsIndexRouteImport } from './routes/hotels.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as PaymentCallbackRouteImport } from './routes/payment.callback'
import { Route as HotelsBookingsRouteImport } from './routes/hotels.bookings'
import { Route as HotelsHotelIdRouteImport } from './routes/hotels.$hotelId'
import { Route as CheckoutOrderIdRouteImport } from './routes/checkout.$orderId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSourcingRouteImport } from './routes/admin.sourcing'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminProofsRouteImport } from './routes/admin.proofs'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPaymentMethodsRouteImport } from './routes/admin.payment-methods'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminHotelBookingsRouteImport } from './routes/admin.hotel-bookings'
import { Route as AdminCommissionsRouteImport } from './routes/admin.commissions'
import { Route as AdminCargoPackagesRouteImport } from './routes/admin.cargo-packages'
import { Route as AdminCargoDispatchRouteImport } from './routes/admin.cargo-dispatch'
import { Route as AdminCargoRouteImport } from './routes/admin.cargo'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminCampaignProductsRouteImport } from './routes/admin.campaign-products'
import { Route as SourcingSourcingIdChatRouteImport } from './routes/sourcing.$sourcingId.chat'
import { Route as ReceiptSourcingSourcingIdRouteImport } from './routes/receipt.sourcing.$sourcingId'
import { Route as HotelsVoucherBookingIdRouteImport } from './routes/hotels.voucher.$bookingId'
import { Route as CheckoutSourcingSourcingIdRouteImport } from './routes/checkout.sourcing.$sourcingId'
import { Route as ApiPublicWebhooksGeniuspayRouteImport } from './routes/api/public/webhooks/geniuspay'

const SourcingRoute = SourcingRouteImport.update({
  id: '/sourcing',
  path: '/sourcing',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MlmRoute = MlmRouteImport.update({
  id: '/mlm',
  path: '/mlm',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupageRoute = GroupageRouteImport.update({
  id: '/groupage',
  path: '/groupage',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CargoRoute = CargoRouteImport.update({
  id: '/Cargo',
  path: '/Cargo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsIndexRoute = HotelsIndexRouteImport.update({
  id: '/hotels/',
  path: '/hotels/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment/callback',
  path: '/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsBookingsRoute = HotelsBookingsRouteImport.update({
  id: '/hotels/bookings',
  path: '/hotels/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsHotelIdRoute = HotelsHotelIdRouteImport.update({
  id: '/hotels/$hotelId',
  path: '/hotels/$hotelId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutOrderIdRoute = CheckoutOrderIdRouteImport.update({
  id: '/checkout/$orderId',
  path: '/checkout/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSourcingRoute = AdminSourcingRouteImport.update({
  id: '/sourcing',
  path: '/sourcing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProofsRoute = AdminProofsRouteImport.update({
  id: '/proofs',
  path: '/proofs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentMethodsRoute = AdminPaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHotelBookingsRoute = AdminHotelBookingsRouteImport.update({
  id: '/hotel-bookings',
  path: '/hotel-bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCargoPackagesRoute = AdminCargoPackagesRouteImport.update({
  id: '/cargo-packages',
  path: '/cargo-packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCargoDispatchRoute = AdminCargoDispatchRouteImport.update({
  id: '/cargo-dispatch',
  path: '/cargo-dispatch',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCargoRoute = AdminCargoRouteImport.update({
  id: '/cargo',
  path: '/cargo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignProductsRoute = AdminCampaignProductsRouteImport.update({
  id: '/campaign-products',
  path: '/campaign-products',
  getParentRoute: () => AdminRoute,
} as any)
const SourcingSourcingIdChatRoute = SourcingSourcingIdChatRouteImport.update({
  id: '/$sourcingId/chat',
  path: '/$sourcingId/chat',
  getParentRoute: () => SourcingRoute,
} as any)
const ReceiptSourcingSourcingIdRoute =
  ReceiptSourcingSourcingIdRouteImport.update({
    id: '/receipt/sourcing/$sourcingId',
    path: '/receipt/sourcing/$sourcingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const HotelsVoucherBookingIdRoute = HotelsVoucherBookingIdRouteImport.update({
  id: '/hotels/voucher/$bookingId',
  path: '/hotels/voucher/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSourcingSourcingIdRoute =
  CheckoutSourcingSourcingIdRouteImport.update({
    id: '/checkout/sourcing/$sourcingId',
    path: '/checkout/sourcing/$sourcingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksGeniuspayRoute =
  ApiPublicWebhooksGeniuspayRouteImport.update({
    id: '/api/public/webhooks/geniuspay',
    path: '/api/public/webhooks/geniuspay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Cargo': typeof CargoRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/groupage': typeof GroupageRoute
  '/messages': typeof MessagesRoute
  '/mlm': typeof MlmRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sourcing': typeof SourcingRouteWithChildren
  '/admin/campaign-products': typeof AdminCampaignProductsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/cargo': typeof AdminCargoRoute
  '/admin/cargo-dispatch': typeof AdminCargoDispatchRoute
  '/admin/cargo-packages': typeof AdminCargoPackagesRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/hotel-bookings': typeof AdminHotelBookingsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/proofs': typeof AdminProofsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/sourcing': typeof AdminSourcingRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/hotels/bookings': typeof HotelsBookingsRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/hotels/': typeof HotelsIndexRoute
  '/checkout/sourcing/$sourcingId': typeof CheckoutSourcingSourcingIdRoute
  '/hotels/voucher/$bookingId': typeof HotelsVoucherBookingIdRoute
  '/receipt/sourcing/$sourcingId': typeof ReceiptSourcingSourcingIdRoute
  '/sourcing/$sourcingId/chat': typeof SourcingSourcingIdChatRoute
  '/api/public/webhooks/geniuspay': typeof ApiPublicWebhooksGeniuspayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Cargo': typeof CargoRoute
  '/auth': typeof AuthRoute
  '/groupage': typeof GroupageRoute
  '/messages': typeof MessagesRoute
  '/mlm': typeof MlmRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sourcing': typeof SourcingRouteWithChildren
  '/admin/campaign-products': typeof AdminCampaignProductsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/cargo': typeof AdminCargoRoute
  '/admin/cargo-dispatch': typeof AdminCargoDispatchRoute
  '/admin/cargo-packages': typeof AdminCargoPackagesRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/hotel-bookings': typeof AdminHotelBookingsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/proofs': typeof AdminProofsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/sourcing': typeof AdminSourcingRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/hotels/bookings': typeof HotelsBookingsRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/product/$id': typeof ProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/hotels': typeof HotelsIndexRoute
  '/checkout/sourcing/$sourcingId': typeof CheckoutSourcingSourcingIdRoute
  '/hotels/voucher/$bookingId': typeof HotelsVoucherBookingIdRoute
  '/receipt/sourcing/$sourcingId': typeof ReceiptSourcingSourcingIdRoute
  '/sourcing/$sourcingId/chat': typeof SourcingSourcingIdChatRoute
  '/api/public/webhooks/geniuspay': typeof ApiPublicWebhooksGeniuspayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Cargo': typeof CargoRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/groupage': typeof GroupageRoute
  '/messages': typeof MessagesRoute
  '/mlm': typeof MlmRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sourcing': typeof SourcingRouteWithChildren
  '/admin/campaign-products': typeof AdminCampaignProductsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/cargo': typeof AdminCargoRoute
  '/admin/cargo-dispatch': typeof AdminCargoDispatchRoute
  '/admin/cargo-packages': typeof AdminCargoPackagesRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/hotel-bookings': typeof AdminHotelBookingsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/proofs': typeof AdminProofsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/sourcing': typeof AdminSourcingRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/hotels/bookings': typeof HotelsBookingsRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/hotels/': typeof HotelsIndexRoute
  '/checkout/sourcing/$sourcingId': typeof CheckoutSourcingSourcingIdRoute
  '/hotels/voucher/$bookingId': typeof HotelsVoucherBookingIdRoute
  '/receipt/sourcing/$sourcingId': typeof ReceiptSourcingSourcingIdRoute
  '/sourcing/$sourcingId/chat': typeof SourcingSourcingIdChatRoute
  '/api/public/webhooks/geniuspay': typeof ApiPublicWebhooksGeniuspayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Cargo'
    | '/admin'
    | '/auth'
    | '/groupage'
    | '/messages'
    | '/mlm'
    | '/orders'
    | '/profile'
    | '/sitemap.xml'
    | '/sourcing'
    | '/admin/campaign-products'
    | '/admin/campaigns'
    | '/admin/cargo'
    | '/admin/cargo-dispatch'
    | '/admin/cargo-packages'
    | '/admin/commissions'
    | '/admin/hotel-bookings'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/payment-methods'
    | '/admin/products'
    | '/admin/proofs'
    | '/admin/roles'
    | '/admin/sourcing'
    | '/admin/users'
    | '/checkout/$orderId'
    | '/hotels/$hotelId'
    | '/hotels/bookings'
    | '/payment/callback'
    | '/product/$id'
    | '/admin/'
    | '/hotels/'
    | '/checkout/sourcing/$sourcingId'
    | '/hotels/voucher/$bookingId'
    | '/receipt/sourcing/$sourcingId'
    | '/sourcing/$sourcingId/chat'
    | '/api/public/webhooks/geniuspay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Cargo'
    | '/auth'
    | '/groupage'
    | '/messages'
    | '/mlm'
    | '/orders'
    | '/profile'
    | '/sitemap.xml'
    | '/sourcing'
    | '/admin/campaign-products'
    | '/admin/campaigns'
    | '/admin/cargo'
    | '/admin/cargo-dispatch'
    | '/admin/cargo-packages'
    | '/admin/commissions'
    | '/admin/hotel-bookings'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/payment-methods'
    | '/admin/products'
    | '/admin/proofs'
    | '/admin/roles'
    | '/admin/sourcing'
    | '/admin/users'
    | '/checkout/$orderId'
    | '/hotels/$hotelId'
    | '/hotels/bookings'
    | '/payment/callback'
    | '/product/$id'
    | '/admin'
    | '/hotels'
    | '/checkout/sourcing/$sourcingId'
    | '/hotels/voucher/$bookingId'
    | '/receipt/sourcing/$sourcingId'
    | '/sourcing/$sourcingId/chat'
    | '/api/public/webhooks/geniuspay'
  id:
    | '__root__'
    | '/'
    | '/Cargo'
    | '/admin'
    | '/auth'
    | '/groupage'
    | '/messages'
    | '/mlm'
    | '/orders'
    | '/profile'
    | '/sitemap.xml'
    | '/sourcing'
    | '/admin/campaign-products'
    | '/admin/campaigns'
    | '/admin/cargo'
    | '/admin/cargo-dispatch'
    | '/admin/cargo-packages'
    | '/admin/commissions'
    | '/admin/hotel-bookings'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/payment-methods'
    | '/admin/products'
    | '/admin/proofs'
    | '/admin/roles'
    | '/admin/sourcing'
    | '/admin/users'
    | '/checkout/$orderId'
    | '/hotels/$hotelId'
    | '/hotels/bookings'
    | '/payment/callback'
    | '/product/$id'
    | '/admin/'
    | '/hotels/'
    | '/checkout/sourcing/$sourcingId'
    | '/hotels/voucher/$bookingId'
    | '/receipt/sourcing/$sourcingId'
    | '/sourcing/$sourcingId/chat'
    | '/api/public/webhooks/geniuspay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CargoRoute: typeof CargoRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  GroupageRoute: typeof GroupageRoute
  MessagesRoute: typeof MessagesRoute
  MlmRoute: typeof MlmRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SourcingRoute: typeof SourcingRouteWithChildren
  CheckoutOrderIdRoute: typeof CheckoutOrderIdRoute
  HotelsHotelIdRoute: typeof HotelsHotelIdRoute
  HotelsBookingsRoute: typeof HotelsBookingsRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  ProductIdRoute: typeof ProductIdRoute
  HotelsIndexRoute: typeof HotelsIndexRoute
  CheckoutSourcingSourcingIdRoute: typeof CheckoutSourcingSourcingIdRoute
  HotelsVoucherBookingIdRoute: typeof HotelsVoucherBookingIdRoute
  ReceiptSourcingSourcingIdRoute: typeof ReceiptSourcingSourcingIdRoute
  ApiPublicWebhooksGeniuspayRoute: typeof ApiPublicWebhooksGeniuspayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sourcing': {
      id: '/sourcing'
      path: '/sourcing'
      fullPath: '/sourcing'
      preLoaderRoute: typeof SourcingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mlm': {
      id: '/mlm'
      path: '/mlm'
      fullPath: '/mlm'
      preLoaderRoute: typeof MlmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groupage': {
      id: '/groupage'
      path: '/groupage'
      fullPath: '/groupage'
      preLoaderRoute: typeof GroupageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Cargo': {
      id: '/Cargo'
      path: '/Cargo'
      fullPath: '/Cargo'
      preLoaderRoute: typeof CargoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/': {
      id: '/hotels/'
      path: '/hotels'
      fullPath: '/hotels/'
      preLoaderRoute: typeof HotelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/callback': {
      id: '/payment/callback'
      path: '/payment/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/bookings': {
      id: '/hotels/bookings'
      path: '/hotels/bookings'
      fullPath: '/hotels/bookings'
      preLoaderRoute: typeof HotelsBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$hotelId': {
      id: '/hotels/$hotelId'
      path: '/hotels/$hotelId'
      fullPath: '/hotels/$hotelId'
      preLoaderRoute: typeof HotelsHotelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$orderId': {
      id: '/checkout/$orderId'
      path: '/checkout/$orderId'
      fullPath: '/checkout/$orderId'
      preLoaderRoute: typeof CheckoutOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sourcing': {
      id: '/admin/sourcing'
      path: '/sourcing'
      fullPath: '/admin/sourcing'
      preLoaderRoute: typeof AdminSourcingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/proofs': {
      id: '/admin/proofs'
      path: '/proofs'
      fullPath: '/admin/proofs'
      preLoaderRoute: typeof AdminProofsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payment-methods': {
      id: '/admin/payment-methods'
      path: '/payment-methods'
      fullPath: '/admin/payment-methods'
      preLoaderRoute: typeof AdminPaymentMethodsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hotel-bookings': {
      id: '/admin/hotel-bookings'
      path: '/hotel-bookings'
      fullPath: '/admin/hotel-bookings'
      preLoaderRoute: typeof AdminHotelBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cargo-packages': {
      id: '/admin/cargo-packages'
      path: '/cargo-packages'
      fullPath: '/admin/cargo-packages'
      preLoaderRoute: typeof AdminCargoPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cargo-dispatch': {
      id: '/admin/cargo-dispatch'
      path: '/cargo-dispatch'
      fullPath: '/admin/cargo-dispatch'
      preLoaderRoute: typeof AdminCargoDispatchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cargo': {
      id: '/admin/cargo'
      path: '/cargo'
      fullPath: '/admin/cargo'
      preLoaderRoute: typeof AdminCargoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaign-products': {
      id: '/admin/campaign-products'
      path: '/campaign-products'
      fullPath: '/admin/campaign-products'
      preLoaderRoute: typeof AdminCampaignProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/sourcing/$sourcingId/chat': {
      id: '/sourcing/$sourcingId/chat'
      path: '/$sourcingId/chat'
      fullPath: '/sourcing/$sourcingId/chat'
      preLoaderRoute: typeof SourcingSourcingIdChatRouteImport
      parentRoute: typeof SourcingRoute
    }
    '/receipt/sourcing/$sourcingId': {
      id: '/receipt/sourcing/$sourcingId'
      path: '/receipt/sourcing/$sourcingId'
      fullPath: '/receipt/sourcing/$sourcingId'
      preLoaderRoute: typeof ReceiptSourcingSourcingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/voucher/$bookingId': {
      id: '/hotels/voucher/$bookingId'
      path: '/hotels/voucher/$bookingId'
      fullPath: '/hotels/voucher/$bookingId'
      preLoaderRoute: typeof HotelsVoucherBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/sourcing/$sourcingId': {
      id: '/checkout/sourcing/$sourcingId'
      path: '/checkout/sourcing/$sourcingId'
      fullPath: '/checkout/sourcing/$sourcingId'
      preLoaderRoute: typeof CheckoutSourcingSourcingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/geniuspay': {
      id: '/api/public/webhooks/geniuspay'
      path: '/api/public/webhooks/geniuspay'
      fullPath: '/api/public/webhooks/geniuspay'
      preLoaderRoute: typeof ApiPublicWebhooksGeniuspayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCampaignProductsRoute: typeof AdminCampaignProductsRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminCargoRoute: typeof AdminCargoRoute
  AdminCargoDispatchRoute: typeof AdminCargoDispatchRoute
  AdminCargoPackagesRoute: typeof AdminCargoPackagesRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminHotelBookingsRoute: typeof AdminHotelBookingsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentMethodsRoute: typeof AdminPaymentMethodsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminProofsRoute: typeof AdminProofsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSourcingRoute: typeof AdminSourcingRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCampaignProductsRoute: AdminCampaignProductsRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminCargoRoute: AdminCargoRoute,
  AdminCargoDispatchRoute: AdminCargoDispatchRoute,
  AdminCargoPackagesRoute: AdminCargoPackagesRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminHotelBookingsRoute: AdminHotelBookingsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentMethodsRoute: AdminPaymentMethodsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminProofsRoute: AdminProofsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSourcingRoute: AdminSourcingRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SourcingRouteChildren {
  SourcingSourcingIdChatRoute: typeof SourcingSourcingIdChatRoute
}

const SourcingRouteChildren: SourcingRouteChildren = {
  SourcingSourcingIdChatRoute: SourcingSourcingIdChatRoute,
}

const SourcingRouteWithChildren = SourcingRoute._addFileChildren(
  SourcingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CargoRoute: CargoRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  GroupageRoute: GroupageRoute,
  MessagesRoute: MessagesRoute,
  MlmRoute: MlmRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SourcingRoute: SourcingRouteWithChildren,
  CheckoutOrderIdRoute: CheckoutOrderIdRoute,
  HotelsHotelIdRoute: HotelsHotelIdRoute,
  HotelsBookingsRoute: HotelsBookingsRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  ProductIdRoute: ProductIdRoute,
  HotelsIndexRoute: HotelsIndexRoute,
  CheckoutSourcingSourcingIdRoute: CheckoutSourcingSourcingIdRoute,
  HotelsVoucherBookingIdRoute: HotelsVoucherBookingIdRoute,
  ReceiptSourcingSourcingIdRoute: ReceiptSourcingSourcingIdRoute,
  ApiPublicWebhooksGeniuspayRoute: ApiPublicWebhooksGeniuspayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
